# Generated by Django 6.0 on 2025-12-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="note",
            name="project_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="projects.project",
            ),
        ),
    ]
