# Generated by Django 6.0 on 2025-12-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_alter_note_options_note_project_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="project_id",
            new_name="project",
        ),
    ]
